### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by SowaNMS** [sashakh/waze#11]
(gdb) run
Starting program: /usr/local/bin/waze 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
14:51:11.856 sERROR !!! roadmap_canvas.cpp, line 928 roadmap_canvas_agg_configure, height =572 width=800 	[File: 'roadmap_canvas.cpp'; Line: 928]
14:51:13.395 sERROR !!! roadmap_prompts.c, line 336 prompts.conf not found. 	[File: 'roadmap_prompts.c'; Line: 336]
14:51:13.416 sERROR !!! roadmap_start.c, line 3322 Waze did not close properly 	[File: 'roadmap_start.c'; Line: 3322]
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

Program received signal SIGSEGV, Segmentation fault.
0x00000055555e118c in ?? ()
(gdb) backtrace
#0  0x00000055555e118c in ?? ()
#1  0x0000005555d73ecd in ?? ()
Backtrace stopped: not enough registers or memory available to unwind further

The error occurs after signing in. Credentials are not saved, so next time waze asks for them.

**Comment by HarryBeadle** [comment]
I am also getting this issue

**Comment by sashakh** [comment]
Guys, Please provide gdb backtrace with not stripped version (not ```/usr/local/bin/waze```):
```
$ gdb src/gtk2/gtkroadmap
(gdb) run
(gdb) backtrace
```
